In [1]:
import os

import pandas as pd

# Readin and clean US Census Data

In [2]:

# Get the parent directory using abspath
base_directory = os.path.abspath('../..')

# Corrected file path without the extra dot
file_path = os.path.join(base_directory, '_input_raw_data', 'social_explorer_tract_ancestry_data', 'R13669333_SL140.csv')

# Read the CSV file
ancestry_df = pd.read_csv(file_path)

C:\Users\cjong\AppData\Local\Temp\ipykernel_25740\2269719539.py:8: DtypeWarning: Columns (0,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241) have mixed types. Specify dtype option on import or set low_memory=False.
  ancestry_df = pd.read_csv(file_path)

In [3]:

# Drop the 0th row and reindex
ancestry_df = ancestry_df.drop(ancestry_df.index[0]).reset_index(drop=True)

# Display the first few rows to identify column names
print(ancestry_df.head())

# Filter for columns before and including "Census Tract", and columns including and after "Total Population"
start_col = "Census Tract"
end_col = "Total Population"

# Get column indices
start_idx = ancestry_df.columns.get_loc(start_col)
end_idx = ancestry_df.columns.get_loc(end_col)

# Select the columns
selected_columns = ancestry_df.columns[:start_idx + 1].tolist() + ancestry_df.columns[end_idx:].tolist()
filtered_df = ancestry_df[selected_columns]

filtered_df

          FIPS                               Qualifying Name  \
0  01001020100     Census Tract 201, Autauga County, Alabama
1  01001020200     Census Tract 202, Autauga County, Alabama
2  01001020300     Census Tract 203, Autauga County, Alabama
3  01001020400     Census Tract 204, Autauga County, Alabama
4  01001020501  Census Tract 205.01, Autauga County, Alabama

  State Postal Abbreviation Summary Level Geographic Component   US  \
0                        al           140                   00  NaN
1                        al           140                   00  NaN
2                        al           140                   00  NaN
3                        al           140                   00  NaN
4                        al           140                   00  NaN

  Census Region Census Division State (FIPS Code) County of current residence  \
0           NaN             NaN                01                         001
1           NaN             NaN                01                         001
2           NaN             NaN                01                         001
3           NaN             NaN                01                         001
4           NaN             NaN                01                         001

   ...  \
0  ...
1  ...
2  ...
3  ...
4  ...

  People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): British West Indian  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): Dutch West Indian  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): Haitian  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): Jamaican  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): Trinidadian and Tobagonian  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): U.S. VirgIn Islander  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): West Indian  \
0                                                  0
1                                                  0
2                                                  0
3                                                  5
4                                                  0

  People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): Other West Indian  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  People Reporting Multiple Ancestries: Yugoslavian  \
0                                                 0
1                                                 0
2                                                 0
3                                                 0
4                                                 0

  People Reporting Multiple Ancestries: Other Groups
0                                                160
1                                                 82
2                                                273
3                                                220
4                                                425

[5 rows x 242 columns]

,FIPS,Qualifying Name,State Postal Abbreviation,Summary Level,Geographic Component,US,Census Region,Census Division,State (FIPS Code),County of current residence,...,People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): British West Indian,People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): Dutch West Indian,People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): Haitian,People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): Jamaican,People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): Trinidadian and Tobagonian,People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): U.S. VirgIn Islander,People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): West Indian,People Reporting Multiple Ancestries: West Indian (Except Hispanic Groups): Other West Indian,People Reporting Multiple Ancestries: Yugoslavian,People Reporting Multiple Ancestries: Other Groups
0,01001020100,"Census Tract 201, Autauga County, Alabama",al,140,00,NaN,NaN,NaN,01,001,...,0,0,0,0,0,0,0,0,0,160
1,01001020200,"Census Tract 202, Autauga County, Alabama",al,140,00,NaN,NaN,NaN,01,001,...,0,0,0,0,0,0,0,0,0,82
2,01001020300,"Census Tract 203, Autauga County, Alabama",al,140,00,NaN,NaN,NaN,01,001,...,0,0,0,0,0,0,0,0,0,273
3,01001020400,"Census Tract 204, Autauga County, Alabama",al,140,00,NaN,NaN,NaN,01,001,...,0,0,0,0,0,0,5,0,0,220
4,01001020501,"Census Tract 205.01, Autauga County, Alabama",al,140,00,NaN,NaN,NaN,01,001,...,0,0,0,0,0,0,0,0,0,425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85391,72153750501,"Census Tract 7505.01, Yauco Municipio, Puerto ...",pr,140,0,NaN,NaN,NaN,72,153,...,0,0,0,0,0,0,8,0,0,34
85392,72153750502,"Census Tract 7505.02, Yauco Municipio, Puerto ...",pr,140,0,NaN,NaN,NaN,72,153,...,0,0,0,0,0,0,5,0,0,135
85393,72153750503,"Census Tract 7505.03, Yauco Municipio, Puerto ...",pr,140,0,NaN,NaN,NaN,72,153,...,0,0,0,0,0,0,0,0,0,6
85394,72153750601,"Census Tract 7506.01, Yauco Municipio, Puerto ...",pr,140,0,NaN,NaN,NaN,72,153,...,0,0,0,0,0,0,9,0,0,21
85395,72153750602,"Census Tract 7506.02, Yauco Municipio, Puerto ...",pr,140,0,NaN,NaN,NaN,72,153,...,0,0,0,0,0,0,0,0,0,34

# Readin shapefile data

In [4]:
import geopandas as gpd
import os

# Define the path to the shapefile
base_directory = os.path.abspath('../..')
shapefile_path = os.path.join(base_directory, '_input_raw_data', 'us_census_cartography', 'cb_2022_us_tract_500k')

# Read the shapefile
shapefile = gpd.read_file(shapefile_path)

In [5]:
shapefile

,STATEFP,COUNTYFP,TRACTCE,AFFGEOID,GEOID,NAME,NAMELSAD,STUSPS,NAMELSADCO,STATE_NAME,LSAD,ALAND,AWATER,geometry
0,06,077,005127,1400000US06077005127,06077005127,51.27,Census Tract 51.27,CA,San Joaquin County,California,CT,1960015,0,"POLYGON ((-121.28708 37.83381, -121.28499 37.8..."
1,06,077,003406,1400000US06077003406,06077003406,34.06,Census Tract 34.06,CA,San Joaquin County,California,CT,839414,14789,"POLYGON ((-121.30900 38.02824, -121.30461 38.0..."
2,06,077,004402,1400000US06077004402,06077004402,44.02,Census Tract 44.02,CA,San Joaquin County,California,CT,4346363,0,"POLYGON ((-121.27339 38.10811, -121.27286 38.1..."
3,06,077,001700,1400000US06077001700,06077001700,17,Census Tract 17,CA,San Joaquin County,California,CT,1685934,0,"POLYGON ((-121.26642 37.97530, -121.26453 37.9..."
4,06,077,000401,1400000US06077000401,06077000401,4.01,Census Tract 4.01,CA,San Joaquin County,California,CT,1045658,0,"POLYGON ((-121.31334 37.96416, -121.30553 37.9..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85180,21,117,065700,1400000US21117065700,21117065700,657,Census Tract 657,KY,Kenton County,Kentucky,CT,1210006,2151,"POLYGON ((-84.61516 39.00608, -84.61372 39.006..."
85181,17,031,410600,1400000US17031410600,17031410600,4106,Census Tract 4106,IL,Cook County,Illinois,CT,252245,0,"POLYGON ((-87.60134 41.80087, -87.59668 41.800..."
85182,36,029,007800,1400000US36029007800,36029007800,78,Census Tract 78,NY,Erie County,New York,CT,3742429,509081,"POLYGON ((-78.91406 43.01076, -78.90694 43.013..."
85183,17,043,846603,1400000US17043846603,17043846603,8466.03,Census Tract 8466.03,IL,DuPage County,Illinois,CT,1124782,2639,"POLYGON ((-88.00337 41.92928, -88.00338 41.931..."
85184,26,093,730600,1400000US26093730600,26093730600,7306,Census Tract 7306,MI,Livingston County,Michigan,CT,32580352,1895322,"POLYGON ((-84.02857 42.54616, -83.98551 42.545..."

# Merge geospatial data and us census data

In [6]:


import numpy as np


filtered_df['FIPS'] = filtered_df['FIPS'].astype(np.int64)
shapefile['GEOID'] = shapefile['GEOID'].astype(np.int64)
merged_df = pd.merge(filtered_df, shapefile, left_on='FIPS', right_on='GEOID', how='inner')
merged_df

C:\Users\cjong\AppData\Local\Temp\ipykernel_25740\4038889854.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['FIPS'] = filtered_df['FIPS'].astype(np.int64)

,FIPS,Qualifying Name,State Postal Abbreviation,Summary Level,Geographic Component,US,Census Region,Census Division,State (FIPS Code),County of current residence,...,GEOID,NAME,NAMELSAD,STUSPS,NAMELSADCO,STATE_NAME,LSAD,ALAND,AWATER,geometry
0,1001020100,"Census Tract 201, Autauga County, Alabama",al,140,00,NaN,NaN,NaN,01,001,...,1001020100,201,Census Tract 201,AL,Autauga County,Alabama,CT,9825303,28435,"POLYGON ((-86.50910 32.47349, -86.50577 32.475..."
1,1001020200,"Census Tract 202, Autauga County, Alabama",al,140,00,NaN,NaN,NaN,01,001,...,1001020200,202,Census Tract 202,AL,Autauga County,Alabama,CT,3320818,5669,"POLYGON ((-86.48122 32.47645, -86.48093 32.481..."
2,1001020300,"Census Tract 203, Autauga County, Alabama",al,140,00,NaN,NaN,NaN,01,001,...,1001020300,203,Census Tract 203,AL,Autauga County,Alabama,CT,5349271,9054,"POLYGON ((-86.47087 32.47573, -86.46964 32.478..."
3,1001020400,"Census Tract 204, Autauga County, Alabama",al,140,00,NaN,NaN,NaN,01,001,...,1001020400,204,Census Tract 204,AL,Autauga County,Alabama,CT,6384282,8408,"POLYGON ((-86.45394 32.49318, -86.45308 32.493..."
4,1001020501,"Census Tract 205.01, Autauga County, Alabama",al,140,00,NaN,NaN,NaN,01,001,...,1001020501,205.01,Census Tract 205.01,AL,Autauga County,Alabama,CT,6203654,0,"POLYGON ((-86.43816 32.45069, -86.43773 32.451..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85054,72153750501,"Census Tract 7505.01, Yauco Municipio, Puerto ...",pr,140,0,NaN,NaN,NaN,72,153,...,72153750501,7505.01,Census Tract 7505.01,PR,Yauco Municipio,Puerto Rico,CT,1820185,0,"POLYGON ((-66.87736 18.03493, -66.87529 18.034..."
85055,72153750502,"Census Tract 7505.02, Yauco Municipio, Puerto ...",pr,140,0,NaN,NaN,NaN,72,153,...,72153750502,7505.02,Census Tract 7505.02,PR,Yauco Municipio,Puerto Rico,CT,689930,0,"POLYGON ((-66.86686 18.02211, -66.86632 18.022..."
85056,72153750503,"Census Tract 7505.03, Yauco Municipio, Puerto ...",pr,140,0,NaN,NaN,NaN,72,153,...,72153750503,7505.03,Census Tract 7505.03,PR,Yauco Municipio,Puerto Rico,CT,3298433,1952,"POLYGON ((-66.88788 18.03583, -66.88326 18.036..."
85057,72153750601,"Census Tract 7506.01, Yauco Municipio, Puerto ...",pr,140,0,NaN,NaN,NaN,72,153,...,72153750601,7506.01,Census Tract 7506.01,PR,Yauco Municipio,Puerto Rico,CT,10985104,4527,"POLYGON ((-66.86634 18.01929, -66.85396 18.025..."
85058,72153750602,"Census Tract 7506.02, Yauco Municipio, Puerto ...",pr,140,0,NaN,NaN,NaN,72,153,...,72153750602,7506.02,Census Tract 7506.02,PR,Yauco Municipio,Puerto Rico,CT,17524412,250956,"POLYGON ((-66.87594 18.01481, -66.87406 18.015..."

In [ ]:
# Update it so

In [7]:
import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd

# Assuming 'df' is your DataFrame
gdf = gpd.GeoDataFrame(merged_df, geometry='geometry')